name: UCL Data Pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"   # 09:00 UTC daily (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 0) Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 2) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3) Fetch historical results + odds (Football-Data)
      - name: Fetch Football-Data (historical)
        run: python scripts/fetch_football_data.py

      # 4) Fetch upcoming odds - manual override OR The Odds API
      - name: Fetch Odds (API or manual override)
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
          # Optional (auto-detects if not set): ODDS_SPORT_KEY
          # ODDS_SPORT_KEY: soccer_uefa_champs_league
          # Optional: ODDS_REGIONS: eu,uk,us,au
        run: python scripts/fetch_the_odds_api.py

      # 5) Fetch FBR xG team metrics (free, FBref-sourced)
      - name: Fetch FBR xG (team/league)
        env:
          FBR_API_KEY: ${{ secrets.FBR_API_KEY }}
        run: python scripts/fetch_fbr_xg.py

      # 6) Enrich features (injuries, lineups, refs, stadium travel, xG)
      - name: Enrich features (merge injuries/lineups/refs/stadium/xG)
        run: python scripts/enrich_features.py

      # 7) Build final CSVs in model schema
      - name: Build HIST & UPCOMING for modeling
        run: python scripts/build_hist_and_upcoming.py

      # 8) Validate and print summaries (so council can see the data)
      - name: Validate and summarize datasets
        run: python scripts/validate_data.py

      # 9) Upload artifacts for modeling (you’ll download these for in-chat model)
      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ucl-data
          path: |
            data/HIST_matches.csv
            data/UPCOMING_fixtures.csv
            data/xg_metrics.csv