name: UCL Data Pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Football-Data (historical)
        run: python scripts/fetch_football_data.py

      - name: Fetch Odds (API or manual override)
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/fetch_the_odds_api.py

      - name: Fetch FBR team xG (current/last → hybrid)
        env:
          FBR_API_KEY: ${{ secrets.FBR_API_KEY }}
        run: python scripts/fetch_fbr_team_xg.py

      - name: Enrich features (merge injuries/lineups/refs/stadium/xG)
        run: python scripts/enrich_features.py

      - name: Build HIST & UPCOMING for modeling
        run: python scripts/build_hist_and_upcoming.py

      - name: Validate and summarize datasets
        run: python scripts/validate_data.py

      - name: Upload data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ucl-data
          path: |
            data/HIST_matches.csv
            data/UPCOMING_fixtures.csv
            data/xg_metrics_current.csv
            data/xg_metrics_last.csv
            data/xg_metrics_hybrid.csv
