name: UCL Data Pipeline

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"  # 09:00 UTC daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Football-Data
        run: python scripts/fetch_football_data.py

      - name: Fetch Odds API
        env:
          THE_ODDS_API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python scripts/fetch_the_odds_api.py

      - name: Enrich features
        run: python scripts/enrich_features.py

      - name: Build final HIST & UPCOMING
        run: python scripts/build_hist_and_upcoming.py

      - uses: actions/upload-artifact@v4
        with:
          name: ucl-data
          path: |
            data/HIST_matches.csv
            data/UPCOMING_fixtures.csv
